apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dirgim-test-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dirgim-test-project
    app.kubernetes.io/part-of: dirgim-test-project
  name: dirgim-test-project
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: dirgim-test-project
status:
  loadBalancer: {}
