apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dirgim-test-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dirgim-test-project
    app.kubernetes.io/part-of: dirgim-test-project
  name: dirgim-test-projectky3j
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dirgim-test-project
    weight: 100
status: {}
